ENV['VAGRANT_EXPERIMENTAL'] = 'typed_triggers'

require 'open3'

VM_CPU = 2
VM_MEMORY_GB = 4
VM_ROOT_DISK_SIZE_GB = 15

Vagrant.configure('2') do |config|
  config.vm.box = 'proxmox-ve-amd64'
  config.vm.provider :libvirt do |lv, config|
    lv.memory = VM_MEMORY_GB*1024
    lv.cpus = VM_CPU
    lv.cpu_mode = 'host-passthrough'
    lv.nested = true
    lv.keymap = 'ch'
    lv.machine_virtual_size = VM_ROOT_DISK_SIZE_GB
  end
  ip = '10.10.10.2'
  config.vm.network :private_network,
    ip: ip,
    auto_config: false,
    libvirt__dhcp_enabled: false,
    libvirt__forward_mode: 'none'
  config.vm.provision :shell, path: 'provision.sh', args: ip
  config.vm.provision :shell, path: 'provision-pveproxy-certificate.sh', args: ip
  config.vm.provision :shell, path: 'provision-containers.sh', args: ip
  config.vm.provision :shell, path: 'summary.sh', args: ip
end
