# see https://pve.proxmox.com/wiki/Automated_Installation

[global]
keyboard = "de-ch"
country = "ch"
timezone = "Europe/Zurich"
fqdn = "pve.example.com"
mailto = "pve@example.com"
root_password = "vagrant"

[network]
source = "from-dhcp"

[disk-setup]
disk_list = ["sda"]
filesystem = "ext4"
