---
name: run-vm

on: push
jobs:
  vm-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      # - name: Install arkade
      #   uses: alexellis/setup-arkade@v3
      # - name: Install firecracker
      #   run: |
      #     sudo arkade system install firecracker
      - name: Run microVM
        run: sudo -E ./run-vm.sh
