---
name: build-box

on:
  push:
  workflow_dispatch:

jobs:
  box-builer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Check if box config changed
        id: box_changed
        uses: dorny/paths-filter@v3
        with:
          filters: |
            src:
              - 'proxmox-ve.pkr.hcl'
              - 'provisioners/**'

      - name: Check if box artifact exists
        uses: LIT-Protocol/artifact-exists-action@v0
        id: check_box_exists
        with:
          name: "proxmox-ve-box"

      - name: Setup packer
        if: |
          ${{ steps.check_box_exists.outputs.exists == 'false' }} ||
          ${{ steps.box_changed.outputs.src == 'true' }} ||
          ${{ github.event_name == 'workflow_dispatch' }}
        uses: hashicorp/setup-packer@v3
        with:
          version: latest

      - name: Packer init
        if: |
          ${{ steps.check_box_exists.outputs.exists == 'false' }} ||
          ${{ steps.box_changed.outputs.src == 'true' }} ||
          ${{ github.event_name == 'workflow_dispatch' }}
        run: packer init ./proxmox-ve.pkr.hcl

      - name: Setup QEMU and run build
        if: |
          ${{ steps.check_box_exists.outputs.exists == 'false' }} ||
          ${{ steps.box_changed.outputs.src == 'true' }} ||
          ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system
          sudo make build-libvirt

      - name: Upload box
        if: |
          ${{ steps.check_box_exists.outputs.exists == 'false' }} ||
          ${{ steps.box_changed.outputs.src == 'true' }} ||
          ${{ github.event_name == 'workflow_dispatch' }}
        uses: actions/upload-artifact@v4
        with:
          name: proxmox-ve-box
          path: |
            ./proxmox-ve-amd64-libvirt.box
            ./proxmox-ve-amd64-libvirt.box.json
          retention-days: 90

  setup-cluster:
    needs: box-builer
    runs-on: ubuntu-latest
