---
name: run-vm

on: push
jobs:
  vm-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup packer
        uses: hashicorp/setup-packer@v3
        with:
          version: latest
      - name: Packer init
        run: packer init ./proxmox-ve.pkr.hcl
      - name: Setup QEMU and run build
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system
          make build-libvirt
